name: Android构建
on:
  workflow_dispatch:
    inputs:
      buildBranch:
        description: '输入构建分支(dev/test/master/prod)'
        required: true
        default: 'test'
      uploadArtifact:
        description: '是否将生成的apk上传到 Github Artifact (true/false)'
        required: false
        default: 'false'
      uploadCloud:
        description: '是否将生成的apk上传到蒲公英。(true/false)'
        required: true
        default: 'true'

env:
  GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
  WECOM_WEBHOOK_KEY: ${{ secrets.WECOM_WEBHOOK_KEY }}
  MENTION_MOBILE_LIST: ${{ secrets.MENTION_MOBILE_LIST }}

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get commit message
        run: |
          GIT_MESSAGE="$(git log --format=%B -n 1)"
          date_str=$(date "+%Y-%m-%d %H:%M:%S")
          seconds=$(date -d "$date_str" +%s)
          seconds_new=$(expr $seconds + 28800) 
          echo "COMMIT_MESSAGE=$GIT_MESSAGE" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date -d @$seconds_new "+%Y-%m-%d_%H_%M_%S")" >> $GITHUB_ENV
      - name: Show commit message
        run: |
          echo "$COMMIT_MESSAGE"
          echo "$BUILD_TIME"
          echo "${{ github.event.inputs.buildBranch }}"
      - name: Checkout code
        run: |
          bash ./checkout.sh "${{ github.event.inputs.buildBranch }}"
      - name: Install npm dependencies
        run: |
          npm install --legacy-peer-deps
      - name: Start Build Apk Message
        run: |
          node ./send-startmsg.js "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" "${{ github.event.inputs.uploadCloud }}"  "Android" "${{ github.event.inputs.buildBranch }}"
      - name: Build Android Release
        run: |
          node ./scripts/env.js "${{ github.event.inputs.buildBranch }}"
          cd android && chmod +x ./gradlew && ./gradlew assembleRelease
      - name: Upload Artifact
        if: ${{ github.event.inputs.uploadArtifact == 'true' }}
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
      - name: Upload Artifact Success
        if: ${{ github.event.inputs.uploadArtifact == 'true' }}
        run: |
          npm i request
          node ./send-success.js "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" "${{ github.event.inputs.uploadCloud }}"  "Android"  "${{ github.event.inputs.buildBranch }}"
      - name: Push to Fir
        id: PushToFir
        run: |
          curl -F 'file=@android/app/build/outputs/apk/release/app-release.apk' -F '_api_key=${{ secrets.PGYER_API_KEY }}' https://www.pgyer.com/apiv2/app/upload
        continue-on-error: true
      - name: Send fir error notify
        id: firErrorMessage
        if: steps.PushToFir.outcome != 'success'
        run: |
          node ./send-msg.js "Android 附件同步到蒲公英平台失败。请检查错误重新执行或前往Action直接下载apk文件 \n>[Job RunId](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" "${{ github.event.inputs.buildBranch }}"
      - name: Send finally notify
        run: |
          node ./send-msg.js "Android 构建成功，并同步到蒲公英平台。\n>[Job Link](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) \n>蒲公英地址:[https://www.pgyer.com/dev-tie-apk](https://www.pgyer.com/dev-tie-apk)" "${{ github.event.inputs.buildBranch }}"
      - name: On Failure
        if: ${{ failure() }}
        run: |
          npm i request
          node ./send-error.js "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" "Android" "${{ github.event.inputs.buildBranch }}"
